version: 0.0
os: linux
files:
  - source: /
    destination: /opt/backend
hooks:
  BeforeInstall:
    - location: scripts/deployment/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deployment/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deployment/start_application.sh
      timeout: 300
      runas: root 